Add .NET Core 2.1 support
namecheap/sdk-core-dotnet pull request #1
Opened 2018-09-20 09:33 UTC by Rheopyrin

2018-09-21 11:37 UTC, b1ff commented on Source/Build.bat
> +SET VSTOOLS=%VS150PROCOMNTOOLS%
Is it possible to build solutions with previous version of the studio?
Or either add discovery for 140 or 150 VS tools and choose installed on a specific environment?

2018-09-21 11:37 UTC, b1ff commented on Source/SDK/HttpConnection.cs
> +#endif
Lets move conditional code to a extension for HttpWebRequest in order to keep readability of this method on current level.

2018-09-21 11:37 UTC, b1ff commented on Source/SDK/Manager/ConfigManager.cs
> +            this.configValues = new Dictionary<string, string>();
This empty instance is overridden by next line.

2018-09-21 11:37 UTC, b1ff commented on Source/SDK/Manager/ConfigManager.cs
> +        private void LoadFromJsonFile(string fileName, bool verifyConfiguration)
I would suggest to improve config management a bit for dotnet core:

1. Move JSON config loading to a separate file. It should reduce conditional code in this file, including using statements
2. Introduce Interface for Account properties and implement that interface for both netstandard and .net configuration entities in order to prevent naming mistakes between different platforms
3. Extract code that populates configuration dictionary from the IEnumerable<IAccount> to a cross platform method and reuse it for both implementations.

2018-09-21 11:37 UTC, b1ff commented on Source/SDK/Manager/ConfigManager.cs
> +            if (paypalConfigSection == null)
Not sure whether it will work with configuration section. It seems that correct way is to use `Exists` method

https://docs.microsoft.com/ru-ru/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1#exists

2018-09-21 11:37 UTC, b1ff commented on Source/SDK/Manager/SDKConfigHandler.cs
> +    public class Account
1. Lets move it to separate class
2. Please add XML comment that will explain this class usage
3. Not sure here, but seems that better to make this class sealed + internal.

2018-09-21 11:37 UTC, b1ff commented on Source/SDK/Manager/SDKConfigHandler.cs
> +
Pls remove empty line.

2018-09-21 11:37 UTC, b1ff commented on Source/SDK/PayPal.Core.SDK.NETStandard2.0.csproj
> +    <SignAssembly>true</SignAssembly>
👍  good catch with signing assembly.

2018-09-21 12:02 UTC, b1ff requested changes
Please check notes on code, I think we should improve solution a bit. Let me know if there are any unclear statements.

2018-09-21 12:02 UTC, b1ff commented on Source/SDK/UserAgentHeader.cs
> +                return "NETSTANDARD2.0";
1. Not that what will be chosen for `netstandard2.0`. Shouldn't we leave only one one value?
2. As far as I understand this value will go to user agent string in http request to paypal api. Have you checked whether it breaks API or not?

2018-09-21 12:02 UTC, b1ff commented on Source/SDK/Util/SDKUtil.cs
> +#if !NETSTANDARD && !NETSTANDARD2_0
I think we can omit the whole method for netstandard.

2018-09-21 12:02 UTC, b1ff commented on Source/UnitTests/IPNMessageTest.cs
> +#endif
Shouldn't we do this from the source code, since all tests are failed without this encoding?

2018-09-21 12:02 UTC, b1ff commented on Source/SDK/PayPal.Core.SDK.NETStandard2.0.csproj
> +    <AssemblyOriginatorKeyFile>paypal-open-source.snk</AssemblyOriginatorKeyFile>
Btw I can see that there are 2 key files: `.\Source\paypal-open-source.snk` and `.\Source\SDK\paypal-open-source.snk` and previous projects use `.\Source\paypal-open-source.snk`. I think for the sake of consistency it also has to be used here.

2018-09-21 12:02 UTC, b1ff commented on Source/SDK/Manager/ConfigManager.cs
> +        private void LoadFromJsonFile(string fileName, bool verifyConfiguration)
Also I think it will be useful to Expose method that loads config from IConfigurationRoot, for the applications that might now use files for configuration.
And another thought is that if ConfigManager is a singleton and it exposes method that refreshes configuration then this method for swapping config should be thread safe. This should reduce amount of tricky bugs for users.

2018-09-21 12:02 UTC, b1ff commented on Source/UnitTests/OAuthTokenCredentialTest.cs
> +            }
It seems that it is safe to use reflection based call for any version of .net. So I suggest to remove PrivateType usage and conditional compilation here.

2018-09-22 18:44 UTC, b1ff commented on Source/PayPal.Core.SDK.NETCore2.1.sln
> +﻿
Just thought, that calling .sln and .csproj file with postfix .NETCore2.1 is a bit inaccurate. Dotnet core 2.1 is true only for tests project, since it is explicitly targets netcoreapp2.1, but the SDK project is more about targeting netstandard2. So for the simplicity I suggest to rename all projects and solutions just to .NETCore postfix without particular version.

2018-09-24 07:19 UTC, Rheopyrin commented on Source/Build.bat
> +SET VSTOOLS=%VS150PROCOMNTOOLS%
Fixed.

2018-09-24 07:19 UTC, Rheopyrin commented on Source/SDK/HttpConnection.cs
> +#endif
Fixed.

2018-09-24 07:19 UTC, Rheopyrin commented on Source/SDK/Manager/ConfigManager.cs
> +        private void LoadFromJsonFile(string fileName, bool verifyConfiguration)
Fixed.

2018-09-24 07:20 UTC, Rheopyrin commented on Source/SDK/Manager/ConfigManager.cs
> +            this.configValues = new Dictionary<string, string>();
Fixed.

2018-09-24 07:22 UTC, Rheopyrin commented on Source/UnitTests/IPNMessageTest.cs
> +#endif
Fixed.

2018-09-24 07:22 UTC, Rheopyrin commented on Source/UnitTests/OAuthTokenCredentialTest.cs
> +            }
Fixed.

2018-09-24 07:25 UTC, Rheopyrin commented on Source/SDK/Util/SDKUtil.cs
> +#if !NETSTANDARD && !NETSTANDARD2_0
Fixed.

2018-09-24 07:25 UTC, Rheopyrin commented on Source/SDK/UserAgentHeader.cs
> +                return "NETSTANDARD2.0";
Fixed.

2018-09-24 07:25 UTC, Rheopyrin commented on Source/SDK/PayPal.Core.SDK.NETStandard2.0.csproj
> +    <AssemblyOriginatorKeyFile>paypal-open-source.snk</AssemblyOriginatorKeyFile>
Fixed.

2018-09-24 07:25 UTC, Rheopyrin commented on Source/SDK/Manager/SDKConfigHandler.cs
> +
Fixed.

2018-09-24 07:25 UTC, Rheopyrin commented on Source/SDK/Manager/SDKConfigHandler.cs
> +    public class Account
Fixed.

2018-09-24 07:25 UTC, Rheopyrin commented on Source/SDK/Manager/ConfigManager.cs
> +            if (paypalConfigSection == null)
Fixed.

2018-09-24 08:05 UTC, b1ff commented on Source/SDK/Manager/ConfigManager.cs
> +                }
Pls cleanup trailing spaces.

2018-09-24 08:05 UTC, b1ff commented on Source/SDK/Manager/ConfigurationLoader.cs
> +                    var value = paypalConfigSection[$"accounts:{index}:{accountPropertyName}"];
Do I understand correctly that due to such implementation we don't need `Account` class and `IAccount` interface?
Original idea to introduce them was to give a solid connection between configuration management for dotnet core and .net framework in order to prevent particular errors during introducing changes to configuration. Currently both implementation don't have too much connection between them, so it is possible to add changes to .net framework implementation and miss them for dotnet core.

2018-09-24 08:05 UTC, b1ff commented on Source/SDK/UserAgentHeader.cs
> +                return "NETSTANDARD2_0";
Lets leave here only netstandard without version separation.

2018-09-25 13:24 UTC, Rheopyrin commented on Source/SDK/Manager/ConfigurationLoader.cs
> +                    var value = paypalConfigSection[$"accounts:{index}:{accountPropertyName}"];
CredentialManager class still uses Account class.

2018-09-26 10:12 UTC, b1ff commented on Source/Jenkinsfile.newflow
> +	          //sh "cp ${testResultFolderName}/coverage.cobertura.xml ./${testResultFolderName}/netcore.coverage.xml || echo \"Absent file ${testResultFolderName}/coverage.cobertura.xml\""
Remove commented code.

2018-09-26 10:12 UTC, b1ff commented on Source/Jenkinsfile.newflow
> +  //  zoomCoverageChart: false])
Remove commented code.

2018-09-26 10:12 UTC, b1ff commented on Source/Jenkinsfile.newflow
> +def runTestsInDocker(container, containerParams, testFolder, envParams, testResultFolderName, onFail) {
Remove `envParams`, `containerParams` and their usage since they are not used within the script.

2018-09-26 10:12 UTC, b1ff commented on Source/Jenkinsfile.newflow
> +  }
Remove this separate stage and move publishTestArtifacts to Unit tests stage in try {} finally  block. This separate stage will be useful if you have more than one test run stage, in current solution I believe will only one stage.

2018-09-26 10:12 UTC, b1ff commented on Source/Jenkinsfile.newflow
> +}
Improve code style of whole file: spaces, brackets usage, etc.

2018-09-27 09:46 UTC, Rheopyrin commented on Source/Jenkinsfile.newflow
> +	          //sh "cp ${testResultFolderName}/coverage.cobertura.xml ./${testResultFolderName}/netcore.coverage.xml || echo \"Absent file ${testResultFolderName}/coverage.cobertura.xml\""
Fixed.

2018-09-27 09:46 UTC, Rheopyrin commented on Source/Jenkinsfile.newflow
> +  //  zoomCoverageChart: false])
Fixed.

2018-09-27 09:46 UTC, Rheopyrin commented on Source/Jenkinsfile.newflow
> +def runTestsInDocker(container, containerParams, testFolder, envParams, testResultFolderName, onFail) {
Fixed.

2018-09-27 09:47 UTC, Rheopyrin commented on Source/Jenkinsfile.newflow
> +  }
Fixed.

2018-09-27 09:47 UTC, Rheopyrin commented on Source/Jenkinsfile.newflow
> +}
Fixed.

2018-09-27 10:36 UTC, b1ff commented on Source/Jenkinsfile.newflow
> +}
Remove internal URIs from the git.

2018-09-27 10:37 UTC, b1ff commented on Source/Jenkinsfile.newflow
> +}
Not really, there are some difference between functions definitoin within the file.

2018-09-27 10:41 UTC, b1ff commented on Source/Dockerfile.newflow
> +FROM nc-mss-app-docker.artifactory.corp.namecheap.net/nc/ncpl/ncpl-build:dotnet2.1
Rename file from `Dockerfile.newflow` to `NetCoreBuild.Dockerfile`

2018-09-27 10:41 UTC, b1ff commented on Source/Jenkinsfile.newflow
> +#!/usr/bin/env groovy
Rename file to `DotnetCorePublish.Jenkinsfile`

2018-09-27 11:03 UTC, Rheopyrin commented on Source/Jenkinsfile.newflow
> +}
Moved to environment variables.

2018-09-27 11:03 UTC, Rheopyrin commented on Source/Jenkinsfile.newflow
> +#!/usr/bin/env groovy
Renamed.

2018-09-27 11:03 UTC, Rheopyrin commented on Source/Jenkinsfile.newflow
> +#!/usr/bin/env groovy
Renamed.

2018-09-27 11:29 UTC, b1ff commented on Source/DotnetCorePublish.Jenkinsfile
> +	//		sh "dotnet nuget push Source/SDK/Package -s ${env.ARTIFACTORY_LINK}"
`NUGET_REGISTRY_LINK`

2018-09-27 11:56 UTC, Rheopyrin commented on Source/DotnetCorePublish.Jenkinsfile
> +	//		sh "dotnet nuget push Source/SDK/Package -s ${env.ARTIFACTORY_LINK}"
Renamed.

2018-09-28 07:44 UTC, b1ff approved these changes

2018-09-28 07:46 UTC, merged